CREATE TABLE "users" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"email" varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	"role" varchar(50) DEFAULT 'user' NOT NULL,
	"created_at" varchar(100) NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "wishes" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"slug" varchar(255) NOT NULL,
	"template_id" varchar(255) NOT NULL,
	"occasion" varchar(100) NOT NULL,
	"title" varchar(255) NOT NULL,
	"subtitle" varchar(255),
	"description" text,
	"recipient" jsonb NOT NULL,
	"sender" jsonb NOT NULL,
	"messages" jsonb NOT NULL,
	"quote" text,
	"poem" text,
	"cover_image" varchar(500) NOT NULL,
	"profile_image" varchar(500),
	"gallery" jsonb,
	"video" varchar(500),
	"voice_message" varchar(500),
	"music" varchar(500),
	"theme" varchar(100) NOT NULL,
	"colors" jsonb,
	"font" varchar(100),
	"animation" jsonb,
	"memories" jsonb,
	"timeline" jsonb,
	"gifts" jsonb,
	"countdown" jsonb,
	"is_public" boolean DEFAULT true NOT NULL,
	"allow_comments" boolean DEFAULT true NOT NULL,
	"allow_reactions" boolean DEFAULT true NOT NULL,
	"views" integer DEFAULT 0 NOT NULL,
	"reactions" integer DEFAULT 0 NOT NULL,
	"shares" integer DEFAULT 0 NOT NULL,
	"tags" jsonb,
	"publish_at" varchar(100),
	"created_at" varchar(100) NOT NULL,
	"updated_at" varchar(100) NOT NULL
);
